/**
 * 追跡する企業の定義。このファイルがアプリ全体の起点になる。
 *
 * ここに1社足すと、次がまとめて増える。
 *   - 見出しへの企業タグ付け（aliases）
 *   - Google ニュースの企業別クエリ（gnews: true のとき）
 *   - はてなブックマークの反響取得（buzz: true のとき）
 *   - 自社ニュースリリースの取得（newsUrl があるとき）
 *   - 本国ニュースルームの取得（globalNewsUrl があるとき）
 *
 * newsUrl / globalNewsUrl に含まれる {year} は、取得時に現在の年（JST）へ
 * 置き換わる。年別ページしか静的に読めないサイトのための仕組み。
 */
export type Company = {
  /** 証券コード。非上場なら任意の一意な文字列でよい */
  code: string;
  /** 画面のタグに出る短い名前 */
  short: string;
  /** 正式名称 */
  name: string;
  sector: Sector;
  /** 見出しに現れる表記のゆれ。大小文字と全角半角は自動で吸収する */
  aliases: string[];
  /** 自社お知らせ一覧のURL。省略すると企業リリースは取得しない */
  newsUrl?: string;
  newsKind?: "rss" | "html";
  /**
   * 地域別法人など、1社で複数のお知らせページを持つ場合の追加URL。
   * newsUrl と同じ形式で扱い、タグは1つにまとまる。
   */
  extraNewsUrls?: string[];
  /** 本国・グループ本体のニュースルーム（海外メーカー用） */
  globalNewsUrl?: string;
  globalNewsKind?: "rss" | "html";
  /** Google ニュースで個別クエリを回すか。報道量の多い社だけ */
  gnews?: boolean;
  /** はてなブックマークで反響を追うか。話題になりうる社だけ */
  buzz?: boolean;
  /** はてブの検索語。省略時は name を使う */
  buzzQuery?: string;
  /** 取得できない理由が分かっている場合のメモ。画面には出さない */
  note?: string;
};

export type Sector =
  | "oem"       // 完成車メーカー（国内）
  | "import"    // 輸入車・海外メーカー
  | "truck"     // 商用車
  | "dealer"    // 販売・中古車
  | "retail"    // 用品小売
  | "auction"   // オートオークション
  | "lease"     // リース
  | "rental"    // レンタカー・カーシェア
  | "finance"   // 販売金融・クレジット
  | "parts"     // 部品・素材
  | "logistics" // 物流・輸送
  | "other";

export const SECTOR_LABELS: Record<Sector, string> = {
  oem: "完成車",
  import: "輸入車",
  truck: "商用車",
  dealer: "販売・中古車",
  retail: "用品小売",
  auction: "オークション",
  lease: "リース",
  rental: "レンタカー",
  finance: "販売金融",
  parts: "部品・素材",
  logistics: "物流",
  other: "その他",
};

export const COMPANIES: Company[] = [
  // ───────────────── 完成車（国内） ─────────────────
  { code: "7203", short: "トヨタ", name: "トヨタ自動車", sector: "oem",
    aliases: ["トヨタ", "TOYOTA", "レクサス", "LEXUS"],
    newsUrl: "https://global.toyota/jp/newsroom/", gnews: true, buzz: true },
  { code: "7201", short: "日産", name: "日産自動車", sector: "oem",
    aliases: ["日産", "NISSAN", "ニッサン", "インフィニティ"],
    newsUrl: "https://global.nissannews.com/ja-JP/", gnews: true, buzz: true },
  { code: "7267", short: "ホンダ", name: "本田技研工業", sector: "oem",
    aliases: ["ホンダ", "HONDA", "本田技研", "アキュラ"],
    newsUrl: "https://global.honda/jp/news/", gnews: true, buzz: true,
    buzzQuery: "ホンダ 自動車" },
  { code: "7211", short: "三菱自", name: "三菱自動車工業", sector: "oem",
    aliases: ["三菱自動車", "三菱自", "MITSUBISHI MOTORS"],
    newsUrl: "https://www.mitsubishi-motors.com/jp/newsroom/index.html",
    gnews: true, buzz: true, buzzQuery: "三菱自動車" },
  { code: "7261", short: "マツダ", name: "マツダ", sector: "oem",
    aliases: ["マツダ", "MAZDA"],
    newsUrl: "https://newsroom.mazda.com/ja/publicity/release/", gnews: true, buzz: true },
  { code: "7269", short: "スズキ", name: "スズキ", sector: "oem",
    aliases: ["スズキ", "SUZUKI"], gnews: true, buzz: true,
    note: "リリース一覧がJS描画のため取得不可。報道タブと反響タブで補う" },
  { code: "7270", short: "SUBARU", name: "SUBARU", sector: "oem",
    aliases: ["SUBARU", "スバル"],
    newsUrl: "https://www.subaru.co.jp/news/", gnews: true, buzz: true },
  { code: "tmej", short: "トヨタ東日本", name: "トヨタ自動車東日本", sector: "oem",
    aliases: ["トヨタ自動車東日本", "トヨタ東日本", "TMEJ"],
    newsUrl: "https://www.toyota-ej.co.jp/news/index.php",
    note: "index.html は2024年で更新停止。必ず index.php" },
  { code: "tmk", short: "トヨタ九州", name: "トヨタ自動車九州", sector: "oem",
    aliases: ["トヨタ自動車九州", "トヨタ九州"],
    newsUrl: "https://www.toyota-kyushu.com/news/" },

  // ───────────────── 商用車 ─────────────────
  { code: "7202", short: "いすゞ", name: "いすゞ自動車", sector: "truck",
    aliases: ["いすゞ自動車", "いすゞ", "ISUZU"],
    newsUrl: "https://www.isuzu-global.com/ja/newsroom.html", gnews: true, buzz: true },
  { code: "543A", short: "アーチオン", name: "ARCHION", sector: "truck",
    aliases: ["ARCHION", "アーチオン"],
    newsUrl: "https://archion.co.jp/news/", gnews: true, buzz: true,
    buzzQuery: "ARCHION 日野 三菱ふそう",
    note: "日野と三菱ふそうの持株会社。2026/4/1 東証プライム上場" },
  { code: "hino", short: "日野", name: "日野自動車", sector: "truck",
    aliases: ["日野自動車", "HINO"],
    newsUrl: "https://www.hino.co.jp/corp/news/{year}/", buzz: true,
    note: "2026/3/30 上場廃止。/corp/news/ はJS描画のため年別ページを使う" },
  { code: "fuso", short: "三菱ふそう", name: "三菱ふそうトラック・バス", sector: "truck",
    aliases: ["三菱ふそう", "FUSO", "Mitsubishi Fuso"],
    newsUrl: "https://www.mitsubishi-fuso.com/jp/newsroom/", buzz: true },

  // ───────────────── 輸入車・海外メーカー ─────────────────
  { code: "mercedes", short: "メルセデス", name: "メルセデス・ベンツ日本", sector: "import",
    aliases: ["メルセデス・ベンツ", "メルセデス", "ベンツ", "Mercedes-Benz", "AMG", "マイバッハ"],
    newsUrl: "https://media.mercedes-benz.jp/", gnews: true, buzz: true,
    buzzQuery: "メルセデス・ベンツ",
    note: "本国 group.mercedes-benz.com は日付が出ず取得不可。本国分は報道タブで補う" },
  { code: "bmw", short: "BMW", name: "ビー・エム・ダブリュー", sector: "import",
    aliases: ["BMW", "ビー・エム・ダブリュー", "MINI", "BMW Motorrad"],
    newsUrl: "https://www.press.bmwgroup.com/japan/article",
    globalNewsUrl: "https://www.press.bmwgroup.com/global/rss.html",
    gnews: true, buzz: true },
  { code: "vw", short: "VW", name: "フォルクスワーゲン グループ ジャパン", sector: "import",
    aliases: ["フォルクスワーゲン", "Volkswagen", "VW"],
    newsUrl: "https://www.volkswagen.co.jp/ja/volkswagen/news.html",
    globalNewsUrl: "https://www.volkswagen-group.com/en/press-releases",
    gnews: true, buzz: true, buzzQuery: "フォルクスワーゲン" },
  { code: "audi", short: "アウディ", name: "アウディ ジャパン", sector: "import",
    aliases: ["アウディ", "Audi"],
    newsUrl: "https://www.audi-press.jp/press-releases/",
    globalNewsUrl: "https://www.audi.com/en/press-releases",
    gnews: true, buzz: true },
  { code: "porsche", short: "ポルシェ", name: "ポルシェ ジャパン", sector: "import",
    aliases: ["ポルシェ", "Porsche"],
    globalNewsUrl: "https://newsroom.porsche.com/en.rss", globalNewsKind: "rss",
    gnews: true, buzz: true,
    note: "日本法人のプレスサイトはボット判定で取得不可。本国はRSSあり" },
  { code: "ferrari", short: "フェラーリ", name: "フェラーリ", sector: "import",
    aliases: ["フェラーリ", "Ferrari"], gnews: true, buzz: true,
    note: "日本・本国とも一覧の取得不可。報道タブのみ" },
  { code: "tesla", short: "テスラ", name: "テスラ", sector: "import",
    aliases: ["テスラ", "Tesla", "サイバートラック"],
    globalNewsUrl: "https://ir.tesla.com/press-releases",
    gnews: true, buzz: true,
    note: "本国はIR発表のみ。製品ニュースは報道タブで拾う" },
  { code: "byd", short: "BYD", name: "BYD Auto Japan", sector: "import",
    aliases: ["BYD", "ビーワイディー", "比亜迪"],
    newsUrl: "https://byd-pr.jp/press/", gnews: true, buzz: true },
  { code: "volvo", short: "ボルボ", name: "ボルボ・カー・ジャパン", sector: "import",
    aliases: ["ボルボ", "Volvo"],
    newsUrl: "https://jp.volvocars.com/pressrelease/release/", gnews: true, buzz: true },
  { code: "gm", short: "GM", name: "ゼネラルモーターズ", sector: "import",
    aliases: ["ゼネラルモーターズ", "General Motors", "GM", "シボレー", "キャデラック"],
    globalNewsUrl: "https://investor.gm.com/rss/news-releases.xml", globalNewsKind: "rss",
    gnews: true, buzz: true, buzzQuery: "ゼネラルモーターズ",
    note: "本国はIR発表のみ" },
  { code: "ford", short: "フォード", name: "フォード", sector: "import",
    aliases: ["フォード", "Ford"], gnews: true,
    note: "2016年末に日本撤退。本国メディアサイトも日付が出ず取得不可" },
  { code: "hyundai", short: "ヒョンデ", name: "Hyundai Mobility Japan", sector: "import",
    aliases: ["ヒョンデ", "Hyundai", "現代自動車", "ヒュンダイ"],
    newsUrl: "https://www.hyundai.com/jp/customer-service/notice",
    globalNewsUrl: "https://www.hyundai.com/worldwide/en/newsroom",
    gnews: true, buzz: true,
    note: "日本法人のプレスリリース欄はJS描画。顧客向けお知らせで代替" },
  { code: "tata", short: "タタ", name: "タタ・モーターズ", sector: "import",
    aliases: ["タタ・モーターズ", "タタモーターズ", "Tata Motors"], gnews: true,
    note: "日本法人なし。報道タブのみ" },
  { code: "renault", short: "ルノー", name: "ルノー・ジャポン", sector: "import",
    aliases: ["ルノー", "Renault"], gnews: true, buzz: true,
    note: "日本・本国とも WAF で取得不可。報道タブのみ" },
  // ───────────────── 販売・中古車 ─────────────────
  { code: "7593", short: "VTHD", name: "VTホールディングス", sector: "dealer",
    aliases: ["VTホールディングス", "ＶＴホールディングス", "VTHD"], gnews: true },
  { code: "9856", short: "ケーユーHD", name: "ケーユーホールディングス", sector: "dealer",
    aliases: ["ケーユーホールディングス", "ケーユー"],
    newsUrl: "https://www.ku-hd.com/ir" },
  { code: "7599", short: "IDOM", name: "IDOM", sector: "dealer",
    aliases: ["IDOM", "イドム", "ガリバー"],
    newsUrl: "https://www.idom-inc.com/news/", gnews: true, buzz: true,
    buzzQuery: "IDOM ガリバー" },
  { code: "3186", short: "ネクステージ", name: "ネクステージ", sector: "dealer",
    aliases: ["ネクステージ", "NEXTAGE"],
    newsUrl: "https://www.nextage.jp/information/news/index.html", gnews: true, buzz: true },
  { code: "wecars", short: "WECARS", name: "WECARS", sector: "dealer",
    aliases: ["WECARS", "ウィーカーズ"],
    newsUrl: "https://www.wecars.co.jp/company/news/", gnews: true, buzz: true },
  { code: "3184", short: "ICDA", name: "ICDAホールディングス", sector: "dealer",
    aliases: ["ICDAホールディングス", "ＩＣＤＡ"],
    newsUrl: "https://ir.icda.jp/ja/irnews.html",
    note: "コーポレートサイトのお知らせは403。IRニュースで代替" },
  { code: "3538", short: "ウイルプラス", name: "ウイルプラスホールディングス", sector: "dealer",
    aliases: ["ウイルプラスホールディングス", "ウイルプラス"],
    note: "お知らせ一覧がJS描画のため取得不可" },
  { code: "8291", short: "日産東京", name: "日産東京販売ホールディングス", sector: "dealer",
    aliases: ["日産東京販売ホールディングス", "日産東京販売"],
    note: "サイトがリダイレクトループで取得不可" },
  { code: "7602", short: "レダックス", name: "レダックス", sector: "dealer",
    aliases: ["レダックス", "Ledax", "カーチス"],
    note: "旧カーチスホールディングス。サイト全体が403" },
  { code: "entetsu", short: "遠州鉄道", name: "遠州鉄道", sector: "dealer",
    aliases: ["遠州鉄道", "遠鉄"],
    note: "お知らせ一覧がJS描画のため取得不可" },

  // ───────────────── 用品小売 ─────────────────
  { code: "9832", short: "オートバックス", name: "オートバックスセブン", sector: "retail",
    aliases: ["オートバックスセブン", "オートバックス", "AUTOBACS"],
    newsUrl: "https://www.autobacs.co.jp/ja/news.html", gnews: true, buzz: true },
  { code: "9882", short: "イエローハット", name: "イエローハット", sector: "retail",
    aliases: ["イエローハット", "YELLOW HAT"], gnews: true, buzz: true,
    note: "サイト全体が403（ボット遮断）" },
  { code: "2788", short: "アップルインター", name: "アップルインターナショナル", sector: "retail",
    aliases: ["アップルインターナショナル"],
    note: "お知らせ一覧がJS描画のため取得不可" },

  // ───────────────── オークション ─────────────────
  { code: "4732", short: "USS", name: "ユー・エス・エス", sector: "auction",
    aliases: ["ユー・エス・エス", "USS"],
    newsUrl: "https://www.ussnet.co.jp/ir/news/index.html", gnews: true,
    note: "一般ニュース欄は2024年で更新停止。IRニュースを使う" },
  { code: "usec", short: "トヨタユーゼック", name: "トヨタユーゼック", sector: "auction",
    aliases: ["トヨタユーゼック", "ユーゼック"],
    newsUrl: "https://www.toyota-usec.co.jp/news/" },
  { code: "utec", short: "ホンダユーテック", name: "ホンダユーテック", sector: "auction",
    aliases: ["ホンダユーテック", "ユーテック"],
    note: "お知らせ一覧ページ自体が存在しない" },

  // ───────────────── レンタカー ─────────────────
  { code: "4666", short: "パーク24", name: "パーク24", sector: "rental",
    aliases: ["パーク24", "タイムズ", "タイムズカー", "Times CAR"],
    newsUrl: "https://www.park24.co.jp/news/index.html", gnews: true, buzz: true },
  { code: "nrc", short: "ニッポンレンタカー", name: "ニッポンレンタカーサービス", sector: "rental",
    aliases: ["ニッポンレンタカー"],
    newsUrl: "https://www.nipponrentacar.co.jp/news.htm" },
  { code: "trc", short: "トヨタレンタカー", name: "トヨタモビリティサービス", sector: "rental",
    aliases: ["トヨタレンタカー", "トヨタレンタリース", "トヨタモビリティサービス"],
    newsUrl: "https://rent.toyota.co.jp/notice/?site=1&member=5" },
  { code: "ncrs", short: "日産レンタカー", name: "日産カーレンタルソリューション", sector: "rental",
    aliases: ["日産カーレンタルソリューション", "日産レンタカー"],
    note: "お知らせ一覧がJS描画のため取得不可" },

  // ───────────────── 販売金融・リース ─────────────────
  { code: "8584", short: "ジャックス", name: "ジャックス", sector: "finance",
    aliases: ["ジャックス", "JACCS"], gnews: true },
  { code: "8585", short: "オリコ", name: "オリエントコーポレーション", sector: "finance",
    aliases: ["オリエントコーポレーション", "オリコ"], gnews: true },
  { code: "7199", short: "プレミアG", name: "プレミアグループ", sector: "finance",
    aliases: ["プレミアグループ", "カープレミア"],
    newsUrl: "https://ir.premium-group.co.jp/ja/news.html" },
  { code: "tfc", short: "トヨタファイナンス", name: "トヨタファイナンス", sector: "finance",
    aliases: ["トヨタファイナンス"],
    newsUrl: "https://www.toyota-finance.co.jp/newsrelease/" },
  { code: "hfc", short: "ホンダファイナンス", name: "ホンダファイナンス", sector: "finance",
    aliases: ["ホンダファイナンス"],
    newsUrl: "https://www.honda.co.jp/HFC/about/index.html",
    note: "独立ドメインなし。親会社サイト内の会社情報ページに掲載" },
  { code: "nfs", short: "日産FS", name: "日産フィナンシャルサービス", sector: "finance",
    aliases: ["日産フィナンシャルサービス"],
    newsUrl: "https://www.nissan-fs.co.jp/news/index.html" },
  { code: "mmcf", short: "三菱自ファイナンス", name: "三菱自動車ファイナンス", sector: "finance",
    aliases: ["三菱自動車ファイナンス"],
    note: "SSL証明書の検証エラーで取得不可" },
  { code: "orixauto", short: "オリックス自動車", name: "オリックス自動車", sector: "lease",
    aliases: ["オリックス自動車"],
    newsUrl: "https://www.orix.co.jp/auto/press/" },
  { code: "smauto", short: "住友三井AS", name: "住友三井オートサービス", sector: "lease",
    aliases: ["住友三井オートサービス"],
    newsUrl: "https://www.smauto.co.jp/news/index.html",
    note: "末尾 index.html が必須。ディレクトリ形式はリダイレクトループ" },
  { code: "mal", short: "三菱オートリース", name: "三菱オートリース", sector: "lease",
    aliases: ["三菱オートリース"],
    newsUrl: "https://www.mitsubishi-autolease.com/info/" },
  { code: "oal", short: "オリコオートリース", name: "オリコオートリース", sector: "lease",
    aliases: ["オリコオートリース"],
    newsUrl: "https://www.oal-net.co.jp/topics/" },
  { code: "ncs", short: "日本カーソリュ", name: "日本カーソリューションズ", sector: "lease",
    aliases: ["日本カーソリューションズ"],
    newsUrl: "https://www.ncsol.co.jp/notice/news.html" },

  // ───────────────── 部品・素材 ─────────────────
  { code: "6902", short: "デンソー", name: "デンソー", sector: "parts",
    aliases: ["デンソー", "DENSO"],
    newsUrl: "https://www.denso.com/jp/ja/news/newsroom/", gnews: true, buzz: true },
  { code: "7259", short: "アイシン", name: "アイシン", sector: "parts",
    aliases: ["アイシン", "AISIN"],
    newsUrl: "https://www.aisin.com/jp/news/topics/", gnews: true,
    note: "公式のニュースリリース一覧は403。トピックス一覧で代替" },
  { code: "3116", short: "トヨタ紡織", name: "トヨタ紡織", sector: "parts",
    aliases: ["トヨタ紡織"],
    newsUrl: "https://www.toyota-boshoku.com/jp/news/" },
  { code: "6201", short: "豊田自動織機", name: "豊田自動織機", sector: "parts",
    aliases: ["豊田自動織機", "トヨタ自動織機"],
    newsUrl: "https://www.toyota-shokki.co.jp/news/", gnews: true,
    note: "TOBにより2026年6月に上場廃止" },
  { code: "5482", short: "愛知製鋼", name: "愛知製鋼", sector: "parts",
    aliases: ["愛知製鋼"],
    newsUrl: "https://www.aichi-steel.co.jp/news/" },
  { code: "6473", short: "ジェイテクト", name: "ジェイテクト", sector: "parts",
    aliases: ["ジェイテクト", "JTEKT"],
    newsUrl: "https://www.jtekt.co.jp/news/" },
  { code: "7282", short: "豊田合成", name: "豊田合成", sector: "parts",
    aliases: ["豊田合成"],
    newsUrl: "https://www.toyoda-gosei.co.jp/news/" },
  { code: "8015", short: "豊田通商", name: "豊田通商", sector: "other",
    aliases: ["豊田通商", "豊通"],
    newsUrl: "https://www.toyota-tsusho.com/press/", gnews: true },
  { code: "tmp", short: "トヨタMP", name: "トヨタモビリティパーツ", sector: "parts",
    aliases: ["トヨタモビリティパーツ", "ジェームス"],
    newsUrl: "https://toyota-mp.co.jp/news/" },
  { code: "7296", short: "FCC", name: "エフ・シー・シー", sector: "parts",
    aliases: ["エフ・シー・シー", "エフシーシー", "FCC"],
    newsUrl: "https://www.fcc-net.co.jp/news/index.php" },
  { code: "7212", short: "エフテック", name: "エフテック", sector: "parts",
    aliases: ["エフテック", "F-TECH"],
    newsUrl: "https://www.ftech.co.jp/topics/" },
  { code: "3422", short: "J-MAX", name: "J-MAX", sector: "parts",
    aliases: ["J-MAX", "ジェイマックス"],
    newsUrl: "https://www.jp-jmax.co.jp/news/",
    note: "正しいドメインは jp-jmax.co.jp" },
  { code: "7218", short: "田中精密", name: "田中精密工業", sector: "parts",
    aliases: ["田中精密工業"],
    newsUrl: "https://www.tanasei.co.jp/news_topics" },
  { code: "7220", short: "武蔵精密", name: "武蔵精密工業", sector: "parts",
    aliases: ["武蔵精密工業", "武蔵精密"],
    newsUrl: "https://www.musashi.co.jp/newsrelease/" },
  { code: "5988", short: "パイオラックス", name: "パイオラックス", sector: "parts",
    aliases: ["パイオラックス", "PIOLAX"],
    newsUrl: "https://www.piolax.co.jp/jp/news/" },
  { code: "7215", short: "ファルテック", name: "ファルテック", sector: "parts",
    aliases: ["ファルテック", "FALTEC"],
    newsUrl: "https://faltec.co.jp/news/" },
  { code: "5949", short: "ユニプレス", name: "ユニプレス", sector: "parts",
    aliases: ["ユニプレス", "Unipres"],
    newsUrl: "https://www.unipres.co.jp/news" },
  { code: "7294", short: "ヨロズ", name: "ヨロズ", sector: "parts",
    aliases: ["ヨロズ"],
    newsUrl: "https://yorozu-corp.co.jp/news" },
  { code: "7239", short: "タチエス", name: "タチエス", sector: "parts",
    aliases: ["タチエス", "TACHI-S"],
    newsUrl: "https://www.tachi-s.co.jp/news/" },
  { code: "5989", short: "エイチワン", name: "エイチワン", sector: "parts",
    aliases: ["エイチワン", "H-ONE"],
    note: "お知らせ一覧がJS描画のため取得不可" },
  { code: "5970", short: "ジーテクト", name: "ジーテクト", sector: "parts",
    aliases: ["ジーテクト", "G-TEKT"],
    note: "お知らせ一覧がJS描画のため取得不可" },
  { code: "7313", short: "TSテック", name: "テイ・エス テック", sector: "parts",
    aliases: ["テイ・エス テック", "テイエステック", "TSテック", "TS TECH"],
    note: "お知らせ一覧がJS描画のため取得不可" },
  { code: "3434", short: "アルファ", name: "アルファ", sector: "parts",
    aliases: ["株式会社アルファ"],
    note: "JS描画で取得不可。社名が一般語のため aliases は完全一致のみ" },
  { code: "7222", short: "日産車体", name: "日産車体", sector: "parts",
    aliases: ["日産車体"],
    note: "お知らせ一覧がJS描画のため取得不可" },
  { code: "7256", short: "河西工業", name: "河西工業", sector: "parts",
    aliases: ["河西工業"],
    note: "お知らせ一覧がJS描画のため取得不可" },
  { code: "nps", short: "日産部品", name: "日産部品販売会社", sector: "parts",
    aliases: ["日産部品中央販売", "日産部品近畿販売", "日産部品九州販売",
              "日産部品埼玉販売", "日産部品群馬販売", "日産部品茨城販売",
              "日産部品東海販売", "日産部品北海道販売", "日産部品千葉販売",
              "日産部品新潟販売", "日産部品長野販売", "日産部品北陸販売",
              "日産部品宮城販売", "日産部品福島販売", "日産部品山形販売",
              "日産部品秋田販売", "日産部品岩手販売", "日産部品青森販売",
              "日産部品栃木販売", "日産部品山陰販売", "日産部品山陽販売",
              "日産部品東四国販売", "日産部品西四国販売", "日産部品沖縄販売",
              "日産部品販売"],
    newsUrl: "https://buhin.nissan.co.jp/CHUO/index.html",
    extraNewsUrls: [
      "https://nissan-buhin-gunma.co.jp/news-all",
      "https://www.nissan-buhin-ibaraki.jp/",
      "https://buhin.nissan.co.jp/KYUSHU/index.html",
      "https://buhin.nissan.co.jp/SAITAMA/index.html",
      "https://buhin.nissan.co.jp/NIIGATA/index.html",
      "https://buhin.nissan.co.jp/NAGANO/index.html",
      "https://buhin.nissan.co.jp/HOKURIKU/index.html",
      "https://buhin.nissan.co.jp/MIYAGI/index.html",
      "https://buhin.nissan.co.jp/FUKUSHIMA/index.html",
      "https://buhin.nissan.co.jp/YAMAGATA/index.html",
      "https://buhin.nissan.co.jp/AKITA/index.html",
      "https://buhin.nissan.co.jp/IWATE/index.html",
      "https://buhin.nissan.co.jp/SANIN/index.html",
      "https://buhin.nissan.co.jp/SANYO/index.html",
      "https://buhin.nissan.co.jp/NISHISHIKOKU/index.html",
    ],
    note: "全国24法人。うち16法人のトップページ What's New から取得。北海道・千葉・東海・東四国はSSL証明書の問題、近畿・沖縄はお知らせ欄なし、青森・栃木はサイト未確認" },

  // ───────────────── 物流・その他 ─────────────────
  { code: "9028", short: "ゼロ", name: "ゼロ", sector: "logistics",
    aliases: ["株式会社ゼロ", "ゼログループ"],
    newsUrl: "https://www.zero-group.co.jp/news/",
    note: "社名が一般語のため aliases は完全一致のみ" },
  { code: "toyotayusou", short: "トヨタ輸送", name: "トヨタ輸送", sector: "logistics",
    aliases: ["トヨタ輸送"],
    newsUrl: "https://www.toyotayusou.co.jp/news.php" },
  { code: "hondalogi", short: "ホンダロジ", name: "ホンダロジスティクス", sector: "logistics",
    aliases: ["ホンダロジスティクス"],
    newsUrl: "https://www.honda-logistics.co.jp/",
    note: "専用の一覧ページはなくトップページのお知らせ欄のみ。更新は年数件" },
  { code: "woven", short: "ウーブン", name: "ウーブン・バイ・トヨタ", sector: "other",
    aliases: ["ウーブン・バイ・トヨタ", "ウーブンバイトヨタ", "Woven by Toyota"],
    newsUrl: "https://woven.toyota/jp/news/", gnews: true, buzz: true },
  { code: "tcd", short: "TCD", name: "トヨタカスタマイジング＆ディベロップメント", sector: "other",
    aliases: ["トヨタカスタマイジング", "モデリスタ", "MODELLISTA", "TRD"],
    note: "お知らせ一覧がJS描画のため取得不可" },
];
